### ISSUE TITLE
Expose DMap.name

### ISSUE THREAD

**Issue by develar** [buraksezer/olric#116]
Will be great to expose `DMap.name`.

Use case: error logging like

```
logger.Error("...", zap.String("map", eTagMap.Name))
```

**Comment by buraksezer** [comment]
Hi @develar 

Good idea. I'm going to add this feature in a few days.

**Comment by buraksezer** [comment]
Done. Please use [v0.3.12](https://github.com/buraksezer/olric/releases/tag/v0.3.12) to use that feature.
