### ISSUE TITLE
Config examples

### ISSUE THREAD

**Issue by sebstyle** [buraksezer/olric#120]
Hello!
I've been looking to replace caching using replicated Redis in my golang app with an integrated solution like Olric.
I would like to remove the Redis requirement but the configuration options of Olric are a bit overwhelming..

Could you provide an example or advice on how to implement the following:
- Multiple app instances with embedded Olric that all have the same cached items (JWT with TTL)
- One of these instances is the master (that writes tokens to cache)
- The other instances are slaves that replicate the tokens from the master
- Network connections between instances running Olric should be secure
- Some way to export/import all cached JWT to/from file on the master instance in case the app needs restarting/upgrading

The last item; I do not know if Olric can do this out of the box? If not perhaps tokens written to cache could also be written to a persistent database store but this would add unwanted overhead for a situation that might only occur ever so often (app restart/upgrade)
Perhaps some advice on a shutdown routine that reads all items & corresponding TTL and write that to file?

Any help much appreciated..
Thanks in advance!

**Comment by polarathene** [comment]
> * Some way to export/import all cached JWT to/from file on the master instance in case the app needs restarting/upgrading

Disk persistence requirement is better suited for something like [Badger](https://github.com/dgraph-io/badger) I think. Although the author of Olric has stated they intend to provide a Redis like AOF log for persistence to disk.

If you're dealing with HTTP cache, another project that might interest you is [Souin](https://github.com/Darkweak/Souin) which offers both Badger and Olric as storage backends.

If you only have to persist for explicit restarts and upgrades and not unexpected events (crash/panic, power loss, etc), persisting state may be easier for you.

Note that Olric is distributed, so other nodes can remain up while one goes down for whatever reason AFAIK, this should make your concern for restarts and upgrades less of an issue, especially if the data size isn't that large. I'm not sure on details of how Olric behaves here when bringing another node online, presumably it should be fairly seamless.

---

**Note:** I'm not a Go dev and haven't used Badger or Olric directly myself, only looked into them when assessing Souin for an HTTP cache solution.

**Comment by sebstyle** [comment]
No I'm not dealing with http cache that might be susceptible to more frequent page changes/writes.
The type of data is JWT (write once on auth requests until TTL expires, read often on api requests)

What I need is basically integrated Redis in replication mode where replication & master/slave negotiation happens over secure connections.
So preferably no partitioning/distributed data but all data on all instances.
Redis does:
- stream changes in the data to replicas
- make snapshots in case it can not resume from stream after downtime

Just like to know if Olric can do such things or read opinions on whether I should instead..
- Write my own RPC code that manages a simpler caching solution with no integrated network layer
- Use Redis and accept the overhead of running/configuring it separately and connecting to it instead of directly reading data from ram in app
I noticed the author created a new (documentation) site (https://olric.io/) but it does not have much content yet..

**Comment by buraksezer** [comment]
Hi,

> One of these instances is the master (that writes tokens to cache)

Olric doesn't have a master node. There is a cluster coordinator which is responsible to publish the routing table. Here is some documents about the architecture: https://github.com/buraksezer/olric#architecture

> Network connections between instances running Olric should be secure

Currently, Olric doesn't support TLS. It assumed that the network is secure. Enabling TLS would decrease the performance drastically. 

> Some way to export/import all cached JWT to/from file on the master instance in case the app needs restarting/upgrading

Currently, Olric doesn't support persistence. It may be added in the next year. Olric relies on backup replicas to remaining accessible. 

> Perhaps some advice on a shutdown routine that reads all items & corresponding TTL and write that to file?

Unfortunately, there is no option to export data from the cluster. But there is a workaround to implement that feature. You can create an iterator over a DMap with `Query` method: https://github.com/buraksezer/olric#query

```go
c, err := dm.Query(query.M{"$onKey": query.M{"$regexMatch": "",}})
```

**Comment by ivano85** [comment]
> Currently, Olric doesn't support persistence. It may be added in the next year. Olric relies on backup replicas to remaining accessible.

Hello, I was looking for this feature too. Even if it may be mostly unuseful, would you consider a optional mechanism for securing joining phase? Or something like using a handler to allow or deny new members to join (when in embedded mode)?

**Comment by sebstyle** [comment]
Thanks for the updated documentation and examples, much appreciated.

**Comment by buraksezer** [comment]
@ivano85 Sorry for my extremely late response. 

> , I ask if providing a way to protect just the join operation may be a good idea (something like the interface for members discovering components). 
>
> Once the member is admitted to join the cluster with an external component, some mechanisms would be needed to deny unauthorized writes.

Olric is designed to use in an isolated environment. An authentication option is planned but not implemented yet.

**Comment by buraksezer** [comment]
> Thanks for the updated documentation and examples, much appreciated.

Hi, @sebstyle, did you decide to use Olric in production? I would like to hear your feedback.
