### ISSUE TITLE
Dmap port

### ISSUE THREAD

**Issue by kotyara85** [buraksezer/olric#126]
What's dmap api port? I don't seen one when start olric

**Comment by buraksezer** [comment]
Hi,

There is no specific port for distributed data structures. Olric uses **3320** for communication. **3322** is used by hashicorp/memberlist for cluster membership and failure detection. 

Please take a look at [config.go](https://github.com/buraksezer/olric/blob/489122868693359fdac467cd10d9c5479dcfc252/config/config.go#L145) to understand the configuration parameters better.

**Comment by kotyara85** [comment]
I did look into that. It's pretty clear how to use dmap as an embedded go library, but not as a standalone bin
Thanks

**Comment by buraksezer** [comment]
You can use `olricd` as a standalone Olric node. Here is some documentation: https://github.com/buraksezer/olric#olricd

If you want to build your own service, `olricd` is good as boilerplate code: https://github.com/buraksezer/olric/tree/master/cmd/olricd

**Comment by kotyara85** [comment]
I mean the question was is how to write to map using standalone binary. 
Thanks
