### ISSUE TITLE
Feature request: logging interface

### ISSUE THREAD

**Issue by tliron** [buraksezer/olric#128]
As it stands, it's quite impossible to plug in other logging systems (e.g. distributed logging) into Olric. Only the builtin Go `log` package is supported, which unfortunately is based on a `struct` and not an `interface`, so there's no way to provide other implementations.

Could Olric support its own logging interface so that we can plug in other systems?

**Comment by buraksezer** [comment]
Hi, thank you for reporting this, but it looks too costly to me. `config.Config` struct has the following field:

```go
// LogOutput is the writer where logs should be sent. If this is not
// set, logging will go to stderr by default. You cannot specify both LogOutput
// and Logger at the same time.
LogOutput io.Writer
```

`LogOutput` is useful to integrate other logging systems. Here is a sample: https://github.com/buraksezer/olric/issues/117

**Comment by tliron** [comment]
Thanks, but that is a very hacky solution. It assumes that 1) entire log messages are always sent as a single `Writer.Write` call, and 2) that all log messages follow the aformentioned format.

If we really want the linked method to be the "correct" way to plug in other logging systems then it has be documented and enforced within all of Olric code. This means that Olric should also not send its `LogOutput` to 3rd party libraries, which might not follow the rules mentioned above. All in all this does not seem to me like the best approach -- this is what interfaces are for in Go.

I'm happy to provide a pull request to enable a logging interface, but I want to make sure the community is interested and that the committers would welcome it before putting time into it.

**Comment by buraksezer** [comment]
Yes, it's hacky but there is no standardisation around logging in the Go ecosystem. I think it is still a feasible solution.

> I'm happy to provide a pull request to enable a logging interface, but I want to make sure the community is interested and that the committers would welcome it before putting time into it.

Thank you but, to be honest, I don't want to change the logging format and how the logging works generally.

**Comment by tliron** [comment]
Thank you for being honest. This is not the right project for my company. I wish you the best luck.
