### ISSUE TITLE
The Expire call may result in the key being lost

### ISSUE THREAD

**Issue by soopsio** [buraksezer/olric#13]
`

    for i := 0; i < 10; i++ {
		//c := customType{}
		//c.Field1 = fmt.Sprintf("num: %d", i)
		//c.Field2 = uint64(i)
		c := "aaaa" + strconv.Itoa(i)
		err = dm.PutEx(strconv.Itoa(i), c, 15*time.Second)
		if err != nil {
			log.Printf("Put call failed: %v", err)
		}
	}
	// Read them again.
	for i := 0; i < 10; i++ {
		val, err := dm.Get(strconv.Itoa(i))
		if err != nil {
			log.Printf("Get call failed: %v", err)
		}
		fmt.Println("Get call one:", strconv.Itoa(i), val, reflect.TypeOf(val))
		//fmt.Println(dm.Expire(strconv.Itoa(i), 55*time.Second))
	}

	time.Sleep(3 * time.Second)
	// Read them again.
	for i := 0; i < 10; i++ {
		val, err := dm.Get(strconv.Itoa(i))
		if err != nil {
			log.Printf("Get call failed: %v", err)
		}
		fmt.Println("Get call two:", val, reflect.TypeOf(val))
	}

`
If I open this line of code:
//fmt.Println(dm.Expire(strconv.Itoa(i), 55*time.Second))
![image](https://user-images.githubusercontent.com/32614138/71564971-1c10e200-2ae4-11ea-9097-bafcb49ae970.png)

**Comment by buraksezer** [comment]
Hello,

I couldn't reproduce the problem on my side. Everything works as expected. Would you like to give more details about your setup and write down the steps to reproduce the bug?

Thanks.

**Comment by buraksezer** [comment]
I managed to reproduce the bug and implemented a fix. Could you please approve that the problem has been fixed?

**Comment by soopsio** [comment]
> I managed to reproduce the bug and implemented a fix. Could you please approve that the problem has been fixed?

I have verified that this problem has been solved, thank you!
