### ISSUE TITLE
db.rt.Shutdown panics

### ISSUE THREAD

**Issue by darkweak** [buraksezer/olric#131]
The routing table shutdown (`github.com/buraksezer/olric/olric.go`) throws an error and make a panic because the routing table is nil. It doesn't crash each time but randomly one in two.

**Comment by buraksezer** [comment]
Hi,

Thank you for reporting this. I need a detailed output to debug that error. It's not possible to reproduce it easily here.

**Comment by buraksezer** [comment]
There is no feedback. I'm closing this. Please don't hesitate to re-open this issue, if you have any clue regarding the problem.
