### ISSUE TITLE
Feature request: gRPC layer

### ISSUE THREAD

**Issue by adnang** [buraksezer/olric#141]
I've been looking around for an embedded distributed database library like this for C#, and when I came across olric I saw it fitted my use case quite very well - essentially I want an API that can provide a "control plane" to enable a client application to act as a node in the "data plane" of a distributed database, similar to Cassandra. 

Exposing the olric operations over gRPC could allow me to build this with C#, and any other client language - `olricd` could run in a gRPC mode listening for client requests.

In my use case, the client application would run with olric as a sidecar in a kubernetes pod - where all the olric containers are clustered - and use it to determine which partition of a working dataset it needs to load into memory, so it can in turn accept requests (HTTP, etc) to either perform work over its dataset, or re-route requests the other nodes of the cluster which contain the other partitions (again by querying olric for other members).

This can be extended to further operations like synchronizing updates between replicas of the partitioned dataset, performing leader-election, etc.

Effectively, this would allow a stateless application (backed by a database) to itself become a horizontally scalable database a la Cassandra/MongoDB, keeping the records in memory and scaling by spreading partitions across nodes.

**Comment by buraksezer** [comment]
Hello,

Thank you for your interest. The future versions of Olric are going to use Redis Protocol. You can try out it on [experimental/redcon](https://github.com/buraksezer/olric/tree/experimental/redcon).

It's almost ready for experimenting. For example:

```
redis-cli -p 3320
127.0.0.1:3320> DM.PUT my-dmap my-key my-value
OK
127.0.0.1:3320> DM.GET my-dmap my-key
"my-value"
127.0.0.1:3320>
```

gRPC is not a good choice for Olric. It's too heavyweight and slow for a distributed caching and data structure server. If you still want to use it, you can easily build a compatibility layer over Olric API or Redis protocol implementation.
