### ISSUE TITLE
Add NewDefaultConfig function for hassle-free onboarding new users

### ISSUE THREAD

**Issue by buraksezer** [buraksezer/olric#16]
Currently we doesn't have proper documentation to assist users while creating their own configuration. Configuring Olric in embedded-member deployment scenario can be very tricky. We need to add a new function to `config` package to return a config with sane defaults. 

Check this: https://github.com/buraksezer/olric/issues/9#issuecomment-588569127

**Comment by justinfx** [comment]
Looks like the `Config.Cache` field is left as a nil pointer, when getting a default config from `New()`

```go
oCfg := olricconfig.New("local")
oCfg.Cache.TTLDuration = 3 * 24 * time.Hour

// panic: runtime error: invalid memory address or nil pointer dereference
// [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe7926b]
```

Should all of the fields have sensible default values?

**Comment by buraksezer** [comment]
We can set an empty `config.CacheConfig` to prevent panic but I don't know that how we determine sensible defaults for `TTLDuration`, `MaxKeys` and other values.

**Comment by justinfx** [comment]
If `nil` is expected, and this is the way a user should be custimising it, then ok. Just wanted to make sure:

```go
	oCfg.Cache = &olricconfig.CacheConfig{
		TTLDuration: 3 * 24 * time.Hour,
		MaxInuse:    conf.Int("maxCacheMB") * 1024 * 1024,
	}
```

**Comment by buraksezer** [comment]
I reviewed the config structure again and initialized `CacheConfig` and `Peers`. Here is the commit: https://github.com/buraksezer/olric/commit/ac5cbef9b3c74405baa1c2e7c9fb0ff659f8820e It's in master. Thanks!

**Comment by justinfx** [comment]
Thanks! I have a bunch more questions now that I have my application working with a single embedded olric and have started to spin up 2 local nodes. I will open a new support issue so that I don't overload this ticket.
