### ISSUE TITLE
Shutdown() panic under certain conditions

### ISSUE THREAD

**Issue by aathan** [buraksezer/olric#177]
I believe the code in `func (d *Discovery) Shutdown() error ` must guard against `d.memberList` being nil.

Under certain startup conditions, memberList may not be fully initialized by the time this code runs.
If I can re-create the condition I'll post more details.

**Comment by buraksezer** [comment]
Hi @aathan, thank you for reporting this.

I'll investigate the problem. Is there any traceback for this problem? Which version do you use? `v0.5.x` tree already has a nil check in `Discovery.Shutdown`.

**Comment by buraksezer** [comment]
Hello,

I have backported the fix and released `v0.4.6`. I'm closing this issue now. If you have any further problems or questions, please don't hesitate to open an issue.
