### ISSUE TITLE
Preliminary version of DMap.Query function

### ISSUE THREAD

**Issue by buraksezer** [buraksezer/olric#18]
We need to implement a preliminary version of `Query` function. It would be like the following: 

```go
dm, err := db.NewDMap("mydmap")
if err != nil {
	// handle error
}

q, err := dm.Query(olric.Q{"$onKey": {"$regexMatch": "/foo.?"}})
if err != nil {
	// handle error
}

q.Range(func(key string, value []byte) bool {
	err = dm.Delete(key)
	if err != nil {
		// handle error
	}
})
```

Currently there is no secondary index to query keys($onKeys) or fields in values($onValues). In this preliminary version, it will do full DMap scan in a distributed manner. Later on we can implement a secondary index to query keys and values. The first version will work only for keys. 

See this thread for more info: https://github.com/buraksezer/olric/issues/9#issuecomment-589827614

**Comment by justinfx** [comment]
I've tested this a bit and wanted to give some feedback. I'm using the following to find keys with a certain prefix:

```go
	q, err := c.dmap.Query(
		query.M{"$onKey": query.M{
			"$regexMatch": fmt.Sprintf("^%s", keyPrefix),
			"$options": query.M{
				"$onValue": query.M{"$ignore": true},
			},
		}})
```

On one hand its nice that you came up with a flexible query dsl. On the other hand, I initially had a bug because I misspelled the case of "$onkey". So its easy to make a typo on the query. Also its a little verbose to get a key-only query iterator, but this works.
Thanks!

**Comment by buraksezer** [comment]
> On one hand its nice that you came up with a flexible query dsl. On the other hand, I initially had a bug because I misspelled the case of "$onkey". So its easy to make a typo on the query. Also its a little verbose to get a key-only query iterator, but this works.

I really like this distributed query feature. It will be very useful when we build a secondary index on keys and fields of values. I'm going to focus on distributed queries in one of the next milestones. 

I use MongoDB at my day job. I'm heavily inspired by its query language. It's fine, I think. I'm totally open to new ideas and improvements on the query language for the next releases.  

The development work of this issue is about to be completed. I'll probably merge this branch into the master branch at Monday.

**Comment by buraksezer** [comment]
I merged feature/issue-18 into the master branch. If you have any further questions or find bugs, please open an issue. 

Thank you!

**Comment by justinfx** [comment]
Thanks! I was just looking at this again today and hoped it would be merged so that I could use all of the new features together. Will definitely provide feedback if anything presents a problem.
