### ISSUE TITLE
more flexible encoder to support proto / json payloads

### ISSUE THREAD

**Issue by derekperkins** [buraksezer/olric#196]
Right now the cache supports native Go types + time, and structs that implement `encoding.BinaryMarshaler`. 
https://github.com/buraksezer/olric/blob/a2126a36354d18254e2fa93556ce4ed67d8d96f6/internal/resp/encoder.go#L103-L112

Are you opposed to expanding the scope? The two that make the most sense to me are supporting proto and json encoding, in that order, for performance reasons.

**Comment by buraksezer** [comment]
Hey @derekperkins, thank you for your contribution, but Olric can support any payload by adding a simple wrapper struct that implements the `encoding.BinaryMarshaler` and `encoding.BinaryUnmarshaler` interfaces. This approach shouldn't lead to a performance problem because it's a wrapper struct. 

In addition to that, I'm opposed to adding new dependencies.

**Comment by derekperkins** [comment]
I understand not wanting to add new dependencies, so I'll go ahead and close this.

We're replacing the use of [ristretto](https://github.com/dgraph-io/ristretto), so our devs are used to being able to just `Put` any value, and none of our types implement `encoding.BinaryMarshaler` (see [open protobuf issue](https://github.com/golang/protobuf/issues/210)). It's definitely a learning curve, and while I fully understand your position about wrapper structs and whatnot, requiring it for any struct is a hindrance to adoption. 

I've seen some old issues about [gob encoding](https://github.com/buraksezer/olric/issues/20), which I'm sure were trying to solve this issue, but can be tricky sometimes, so it seems like you've moved away from it. Not sure if there is any more clarity on that.

In any event, we just wrapped the entire `Put` command and are doing the proto mapping ourselves, so we're in a good place. Thanks again.

**Comment by derekperkins** [comment]
Also for the record, I looked into creating a generic constraint that would turn this error from a runtime error into a compile error, but that is currently not allowed, since the constraint would have all the concrete types + `encoder.BinaryMarshaler`

> We've decided not to allow interfaces in unions, for the first version of generics at least
https://github.com/golang/go/issues/45346#issuecomment-862505803
