### ISSUE TITLE
pipelining 100x slower on cache misses

### ISSUE THREAD

**Issue by derekperkins** [buraksezer/olric#198]
We tried switching from individual DMap.Get calls to pipelining today and found very poor performance on cache misses. 

In the trace below, there were 99 keys added to the pipeline. The gap from the beginning of the `Exec` bar and the first `Result` is where `pipeline.Exec` was called, ~300ms. Any `Result()` call followed by a `Scan` means that there was a cache hit, otherwise it was a miss. Cache hits are great, almost all within 0.25-0.50 ms. Cache misses however take up to 150ms before returning. Is that expected behavior? My expectation was that `pipeline.Exec` might take 10-100ms to fetch everything, then any Result() calls afterwards would be almost free.

<img width="658" alt="image" src="https://user-images.githubusercontent.com/3588778/209761994-2eca0f1e-0632-4d6a-a5c9-7484cb0709ed.png">

The spike below is when we deployed pipelining, and the low dots on the right are when we reverted to making the same number of Get calls as there are Pipeline Get + Result calls.

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/3588778/209761707-02385324-2829-42d4-b507-b4f4122d0078.png">

Env:
- Olric v0.5.0
- 30 embedded client cluster
- k8s 1.21

**Comment by buraksezer** [comment]
Hey, @derekperkins Could you please share your configuration? I particularly need to learn the following fields:

* ReplicaCount
* ReadQuorum
* ReadRepair

**Comment by derekperkins** [comment]
I'm not setting any of those explicitly.

```go
cfg := config.New("lan") // default configuration
cfg.ServiceDiscovery = map[string]any{
	"plugin": k8sDisc,
}
cfg.ReplicationMode = config.AsyncReplicationMode
cfg.LogLevel = "WARN"
cfg.LogVerbosity = 1

cfg.DMaps.Custom[name] = config.DMap{
	EvictionPolicy:  config.LRUEviction,
	MaxIdleDuration: 24 * time.Hour,
	MaxInuse:        50_000_000,
}
```

**Comment by derekperkins** [comment]
FWIW, we're caching immutable objects, so stale data isn't possible. We're strictly focused on performance, and can set any knobs to whatever you suggest

**Comment by buraksezer** [comment]
It may be related to https://github.com/buraksezer/olric/issues/201. Initially, I thought we could add an option to disable the Last-Write-Wins policy but `ReplicaCount` is 1 by default. So it's already useless for your configuration.

**Comment by derekperkins** [comment]
I wasn't doing any `Put()` calls in the pipeline, just `Get()`, but there would have been a lot of concurrent `Put` calls happening outside the Pipeline

**Comment by derekperkins** [comment]
And after `Exec()` returns, `Result()` isn't making any network calls, correct? Those should have all been resolved inside `Exec`

**Comment by buraksezer** [comment]
> And after Exec() returns, Result() isn't making any network calls, correct? Those should have all been resolved inside Exec

That's correct.

I checked the code but I couldn't find any reason why cache misses are slow while hits are quite fast. Are cache misses slow with the normal DMap API? The related function is here: https://github.com/buraksezer/olric/blob/9c9188322a7bbf655205b31df081b6f143f3e9fe/internal/dmap/get.go#L276

**Comment by derekperkins** [comment]
> Are cache misses slow with the normal DMap API?

I don't believe so. We first implemented olric without using pipelines or goroutines for `Get` calls, which did cause a slowdown (deployment happened at metric spike) compared to the previous local only cache (ristretto), but nothing unexpected for ~100 sequential network calls.

![image](https://user-images.githubusercontent.com/3588778/210282241-1d55a8d6-9dbb-408d-88e6-78eb42131559.png)

It stabilized at those p-values until we deployed with pipelines (deployment at metric spike), which sent latency through the roof, even though it should have been fundamentally making the same ~100 requests with concurrency of 1.

![image](https://user-images.githubusercontent.com/3588778/210282178-1617913a-4a24-4c39-9d53-920a7c92d7ee.png)

**Comment by derekperkins** [comment]
I just redeployed v0.5.1 and it shows massive improvements over the original trace above, but still is surprisingly slow on cache misses. They aren't taking 100ms now, but calling `Result()` on cache misses is taking ~1 ms, where cache hits take only ~0.02 ms

### Long pipeline.Exec time, almost all cache hits

<img width="521" alt="image" src="https://user-images.githubusercontent.com/3588778/211938162-7f5e45b6-8056-4d47-879a-73707302ad3c.png">

### Short pipeline.Exec time, almost all cache misses

<img width="336" alt="image" src="https://user-images.githubusercontent.com/3588778/211938504-7c14fd54-732f-4f79-b095-12ae16dd6bac.png">

**Comment by derekperkins** [comment]
Never mind, that was my bad. I wasn't ignoring the `KeyNotFound` error, so that handling was taking extra long, skewing the results. 😬
