### ISSUE TITLE
Consul integration for peer discovery

### ISSUE THREAD

**Issue by buraksezer** [buraksezer/olric#21]
Memberlist needs a peers list to operate. Now we need to manage that list manually. It's not ideal for a production environment. We need to integrate Consul for service discovery. 

See this https://github.com/buraksezer/olric/issues/20#issuecomment-594153082

**Comment by buraksezer** [comment]
Hey @justinfx, I've completed the initial implementation. It seems to work fine on my side. But I don't have Consul experience on a production system. So I may have missed something important in design or implementation. 

I have implemented Consul integration as a plugin. I think it's a good design decision to support wide variety of service discovery tools and methods with a common interface in the discovery subsystem of Olric. 

The code in the Olric code base lives on [feature/issue-21](https://github.com/buraksezer/olric/tree/feature/issue-21) and the plugin can be found at https://github.com/buraksezer/olric-consul-plugin. I write something to deploy the plugin but it may be confusing for someone else. 

The plugin interface in Olric:

```go
// ServiceDiscovery is an interface that defines a unified API for service discovery plugins.
type ServiceDiscovery interface {
	// Initialize initializes the plugin: registers some internal data structures, clients etc.
	Initialize() error

	// SetConfig registers plugin configuration
	SetConfig(c map[string]interface{}) error

	// SetLogger sets a logger
	SetLogger(l *log.Logger)

	// Register registers this node to a service discovery directory.
	Register() error

	// Deregister removes this node from a service discovery directory.
	Deregister() error

	// DiscoverPeers returns a list of known Olric nodes.
	DiscoverPeers() ([]string, error)

	// Close stops underlying goroutines, if there is any. It can be a blocking call.
	Close() error
}
```

[olric-consul-plugin](https://github.com/buraksezer/olric-consul-plugin) implements this interface. Would you like to try the plugin? I'm here for quick answers. 

Note: You still need to set two different ports per Olric node.

**Comment by justinfx** [comment]
Very cool. I will try and test this out this week! Quick initial thoughts before I have a chance to play...
Is this going to be a problem? https://github.com/buraksezer/olric/commit/922f80e60ef4e8912962203abdf740aa7c96c7b2#diff-47f7341412bc282c5607e411ce1a35b4R108
Also, do you have any doc examples of how to use the plugin in an embedded situation by just importing the plugin and registering it? It seems excessive to need to build it out as a plugin and load it in if we are already in code and can just directly register it.

**Comment by justinfx** [comment]
I've started to test this out and the thing I wanted straight away was to directly load the plugin as a library and provide it to my embedded cache instance. Its great that you have implemented it as a plugin to be loaded by an `olricd` server, but its a bit heavy to need to build the plugin and reference it on the filesystem for my embedded use. I am working on some changes to accomodate this but it will require a PR to both olric and olric-consul-plugin. I will try and get something pushed up today for you to look at.

**Comment by buraksezer** [comment]
I have just merged the PRs. Thank you very much for your contribution. By the way, I use this snippet to test the plugin in embedded-member mode: https://gist.github.com/buraksezer/2a4f21d33946374a9b0fd82f8e767304

This includes two Olric nodes in the same process and it's important to see that both of the nodes joins the same cluster. I search this line in the logs: `[INFO] Cluster coordinator: 127.0.0.1:PORT`.

It should be seen two times in the logs.

**Comment by justinfx** [comment]
I've managed to get this working with two different instances of my app, running on the same host, using completely random ports at runtime for both the client api port and the cluster bind port. And I only have a few feedback items to get your opinion on.

When I start up the first/only node, I get this log outpu:

```
[INFO] Service discovery plugin is enabled, provider: consul
[ERROR] Join attempt returned error: no peers found
[INFO] Awaits for 1s to join again (1/3)
[ERROR] Join attempt returned error: no peers found
[INFO] Awaits for 1s to join again (2/3)
[ERROR] Join attempt returned error: no peers found
[INFO] Awaits for 1s to join again (3/3)
[INFO] The cluster coordinator has been bootstrapped
```

I wonder if there is a way to improve this start up logic when it is the first and maybe only node for now. Should it really be logged as an error if there are no other peers reported from the service discovery? 

Another small item was a change I made from your documented example of how to do the consul service check. The example used the cluster bind port as the "tcp"check, which for me started causing the node to emit log lines about constant memberlist connections (from consul). I changed the check to use the client api port instead.

**Comment by buraksezer** [comment]
> I wonder if there is a way to improve this start up logic when it is the first and maybe only node for now.

There is no way to know that it is the first and maybe only node for now. If nodes form a new cluster without "try again" logic, this causes a split-brain situation and these partitions have to be merged eventually. If you have only one node, you may set `MaxJoinAttempts` to 1. 

>  Should it really be logged as an error if there are no other peers reported from the service discovery? 

Service discovery plugin is triggered by the discovery subsystem. Any error from `Join` function triggers the retry mechanism. This error may be silenced but I think that there is no need to do that. Moreover it should only be observed at the first moments of the cluster if the network functions normally. 

>  which for me started causing the node to emit log lines about constant memberlist connections (from consul). I changed the check to use the client api port instead.

It's totally fine. 

Thanks!

**Comment by buraksezer** [comment]
Merged into the master. If you have any further questions or problems, please don't hesitate to open a new issue.

**Comment by justinfx** [comment]
As a follow up to this feature, since I already have nat.io integrated in my project as well, I thougth it would be neat to write a service discovery plugin using nats. Please if you have time, take a look at https://github.com/justinfx/olric-nats-plugin
Feedback welcome.

**Comment by buraksezer** [comment]
Great! It's glad to see that. I'll try it as soon as possible. By the way, I'm working on a cloud discovery plugin which uses https://github.com/hashicorp/go-discover. It supports Kubernetes. I'm also testing Olric on Kubernetes against possible integration problems and pitfalls.
