### ISSUE TITLE
why do you use Redis Pubsub

### ISSUE THREAD

**Issue by HoangNgo88** [buraksezer/olric#215]
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me  it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by buraksezer** [comment]
Hi @HoangNgo88, Olric uses [RESP2](https://redis.io/docs/reference/protocol-spec/) as the wire protocol. RabbitMQ and Apache Kafka use entirely different protocols. 

> are there any special features that others dont have it. Can you share me it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

It would be best if you asked these sorts of questions to StackOverflow.
