### ISSUE TITLE
storage overhead per object

### ISSUE THREAD

**Issue by derekperkins** [buraksezer/olric#230]
I'm storing marshaled protobuf bytes in olric, with sizes ~200 bytes. I only have 10k total objects, which would be only about 2 MB in their entirety, however I'm seeing hundreds of megabytes used across the cluster, and > 90% cache misses. It feels like I'm missing something. Is there significant per-object overhead that might explain it?

This is my first time caching non-immutable objects, so I'm using TTL and Delete for the first time. Maybe I'm doing something wrong, though we've successfully served billions of requests through olric elsewhere. Here's the config we're using.

```go
cache.cfg.DMaps.Custom[name] = config.DMap{
	EvictionPolicy:  config.LRUEviction,
	MaxIdleDuration: 24 * time.Hour,
	MaxInuse:        30_000_000, // default to 30 MB
	TTLDuration:     1*time.Hour,
}
```

**Comment by derekperkins** [comment]
I tracked down the cache misses and that was totally self-inflicted. I am still curious about what the per-object overhead is from a RAM usage perspective. Does the `MaxInuse` config include that overhead, or is it just the `key + value` size in bytes?

**Comment by buraksezer** [comment]
Hey @derekperkins,

I'm sorry for not getting back to you sooner. The default storage engine follows a simple approach: 

- Allocates byte arrays on the heap. This is called `table` in Olric terminology. 
- A table is a finite resource and is indexed by a built-in map.
- The index stores the hash of key (uint64) as the key and an offset as the value.
- A storage engine instance may have an infinite number of tables. The tables can be recycled.
- Table implementation can be found here: https://github.com/buraksezer/olric/blob/master/internal/kvstore/table/table.go
- On a table, the memory layout of a key/value pair is this: 
```
KEY-LENGTH(uint8) | KEY(bytes) | TTL(uint64) | TIMESTAMP(uint64) | LASTACCESS(uint64) | VALUE-LENGTH(uint64) | VALUE(bytes)
```
- When a get request hits the storage engine, first it finds the offset from the index and then reads the key/value pair from the table. 
- When you remove a key/value pair from Olric, it's only removed from the index. A background task cleans and recycles the tables. 

You can find the storage engine API here: https://github.com/buraksezer/olric/blob/master/internal/kvstore/kvstore.go

The current implementation uses 29 bytes to store metadata. A built-in map (here it is: `map[uint64]uint64`) has been defined alongside the table. How many bytes have been consumed by the built-in map may depend on your platform and the Golang version.

**Comment by derekperkins** [comment]
Thanks for the detailed response! That answer would be great in the main readme as is
