### ISSUE TITLE
Weird data race when listening to cluster events

### ISSUE THREAD

**Issue by Tochemey** [buraksezer/olric#240]
I am experiencing some weird data race when listening to cluster event as shown in the screenshot
<img width="1031" alt="image" src="https://github.com/buraksezer/olric/assets/1633645/2765aeeb-4756-469d-8ecc-222df3cc67bf">

I am listening to the cluster in the go routine in this sample code:
```
	for {
		select {
		case <-c.listenerStopSignal:
			return
		case message, ok := <-subscriber.Channel():
			// break out of the loop when the channel is closed
			if !ok {
				return
			}
			// grab the message payload
			payload := message.Payload
			// get the message payload
			var event map[string]any
			// let us unmarshal the event
			if err := json.Unmarshal([]byte(payload), &event); err != nil {
	
			}

			// grab the kind
			kind := event["kind"]

			switch kind {
			case events.KindNodeJoinEvent:
				// create the node joined to unmarshal the event
				nodeJoined := new(events.NodeJoinEvent)
				// let us unmarshal the event
				if err := json.Unmarshal([]byte(payload), &nodeJoined); err != nil {
				}


			case events.KindNodeLeftEvent:
				// create the node left to unmarshal the event
				nodeLeft := new(events.NodeLeftEvent)
				// let us unmarshal the event
				if err := json.Unmarshal([]byte(payload), &nodeLeft); err != nil {
		
				}

	
			default:
				// skip
			}
		}
	}
```

**Comment by Tochemey** [comment]
Hello @buraksezer. No to put pressure. I just want to know if the issue is from my code or this is a real bug. It is not consistent though.

**Comment by Tochemey** [comment]
@buraksezer When are we having another release?

**Comment by buraksezer** [comment]
@Tochemey, I saw your deleted message. Please stop sending such messages. This is neither a support forum nor Olric is a paid product. I'm not also your project's advisor. I think you should look over your project yourself. 

A new version can be ready when I have some free time. Olric is a free software project.

**Comment by Tochemey** [comment]
@buraksezer Thanks. closing the issue. Sorry for such messages. I understand it is a free software and I appreciate the fact you took time to look into issue and replied us.

**Comment by Tochemey** [comment]
I deleted the message not because it was not relevant. I just thought it might look like putting pressure because my project depends upon it and I am having a data race issue.
