### ISSUE TITLE
[Support] Distributed mode & NAT

### ISSUE THREAD

**Issue by pojntfx** [buraksezer/olric#25]
I wanted to ask if it is possible to have a distributed setup where not all nodes can talk to each other, but every node can talk to at least one other node. An example:

```plaintext
 +---> Node 1 (10.0.0.1)
 |
 |
 +---> Node 2 (10.0.0.2)                            Node 4 (192.168.178.44, 84.191.14.77)
 |                                                             +
 |                                                             |
 +---+ Node 3 (10.0.0.3, 84.191.14.76)                         |
                                                               |
              ^                                                |
              |                                                |
              +-----------------+  Tunnel  <-------------------+
```

In the README, it is explained that "only one peer is required to discover the complete cluster". Does this mean that a setup such as the one above is possible? If not with the default configuration, is it possible to configure olric in such a way (like with full replication)?

Thanks for any help!

PS: My current distributed olric setup can be found [in this GitHub Repo](https://github.com/pojntfx/gloeth/tree/master/pkg/storage)!

**Comment by pojntfx** [comment]
Just for clarification: In a "normal" scenario, this could probably be fixed by using a VPN. This is not possible in this case because it's a basis for the VPN ;)

**Comment by buraksezer** [comment]
Hi @pojntfx,

Olric is designed to be used in a well-controlled cloud environment such as Amazon EC2 or a Kubernetes cluster. It assumes that network is stable and all nodes can talk to each other. The scenario you mentioned is split-brain case for Olric. You probably need a different kind of DHT implementation such as Kademlia, Chord or Tapestry. Some of them are already implemented in Golang, especially Kademlia:

https://github.com/anacrolix/dht
https://github.com/shiyanhui/dht
https://github.com/arriqaaq/chord

If you have any further questions, please don't hesitate to ask.

**Comment by buraksezer** [comment]
There is a project called God. Implemented in Golang. It's almost dead but I think you may want to know more about it. 

https://github.com/zond/god
http://zond.github.io/god/

**Comment by pojntfx** [comment]
@buraksezer Thanks a lot for your quick answer! You're probably right; my specific usecase requires a lot of non-typical workarounds (such as routing through nodes), so Olric is probably not the right tool for this very specific job.

Thanks anyways for this awesome project!
