### ISSUE TITLE
Olric possible duplication of keys

### ISSUE THREAD

**Issue by tsfotis-nx** [buraksezer/olric#257]
## Description

version: 0.5.4
When repeatedly inserting the same key into a DMap in Olric, a key duplication issue occurs once the `tableSize` limit is reached and reallocation takes place.

## Steps to Reproduce

1. Repeatedly insert the same key-value pair into the DMap
2. Continue inserting until the `tableSize` limit is reached and reallocation occurs

## Expected Behavior

The key should remain unique in the DMap, even after reallocation.

**Comment by buraksezer** [comment]
> When repeatedly inserting the same key into a DMap in Olric, a key duplication issue occurs once the tableSize limit is reached and reallocation takes place.

This is the expected behavior of the storage engine. It simply implements the key/value store with append-only byte arrays indexed by a built-in map. This design reduces the GC pressure.
