### ISSUE TITLE
Olric k8s embedded cluster

### ISSUE THREAD

**Issue by AarshShah33** [buraksezer/olric#258]
Hi, we are trying to use olric in embedded cluster in GCP k8s setup with olric v0.5.4 and using olric-cloud-plugin

The issue we face is this: Initially 2 pods spin up => I put the olric cluster initialisation at almost the entry point of the code as a part of testing, both create a new cluster as both of those nodes are not in ready state initially - So it creates a single node cluster for both

Now my questions are: 

- Can increasing the number of retries fix this issue? 
- Can putting olric at some point later in the codebase make this work? 
- AND MOST IMPORTANTLY - we didn't try this but is there some kind of cluster merging if a 3rd pod spins up and figures out there are 2 clusters running? And if not - will all the new pods that spin up now will join one of the random 2 existing clusters?

**Comment by buraksezer** [comment]
Hey, unfortunately, olric-cloud-plugin is an unmaintained part of Olric.

Your problem may be caused by a network-related issue in your K8s setup. The nodes may fail to discover each other via the olric-cloud-plugin. This should be debugged on your side.

**Comment by AarshShah33** [comment]
sure thanks!
