### ISSUE TITLE
Distributed version of Stats

### ISSUE THREAD

**Issue by buraksezer** [buraksezer/olric#32]
Currently, `Stats` command in the protocol and `olric-stats` tool only work on a cluster member. So if you run the following command:

```bash
olric-stats -a=cluster-member:port
```

It returns statistics for only one cluster member. This is not very useful most of the time. We need to aggregate all statistics. 

`-s/--summary` would also be useful.

**Comment by hiepd** [comment]
@buraksezer I would like to take a look at this issue if no one else is looking at it. Thanks!

**Comment by buraksezer** [comment]
@hiepd, it's yours. I'm always here for help. Thank you!
