### ISSUE TITLE
Move ServiceDiscovery plugin interface out of internal/ path 

### ISSUE THREAD

**Issue by justinfx** [buraksezer/olric#38]
Currently the `ServiceDiscovery` interface is hidden within the internal/ import path, which means external plugin developers can't directly reference it when ensuring they fully implement it. An example of an issue is my [olric-nats-plugin](https://github.com/justinfx/olric-nats-plugin) which started crashing after the plugin interface was changed. I have to manually consult the source code to see the new interface since the internal symbols won't resolve for me in my tooling.
Can this be moved into an exported location within the olric project?

Edit: It is not that the interface was changed, but rather my implementation is not matching and I can't easily line up *why* without the interface being public.

**Comment by buraksezer** [comment]
Thank you for reporting. The fix is merged into master branch. See commit: 8650b650cf90f08377785455b823871df6428dbd
