### ISSUE TITLE
The atomic operation documentation is missing on README.md

### ISSUE THREAD

**Issue by kokizzu** [buraksezer/olric#4]
Incr, Decr, GetPut

**Comment by kokizzu** [comment]
also these parts:

Persistence
Serialization
Golang Client
Standalone Server
Command Line Interface
Operation Modes
Embedded member
Client plus member

**Comment by buraksezer** [comment]
Hello,

This project is WIP. The code evolves too fast and I don't update the documents frequently. I'm going to update or add documents for stabilized features and design decisions. 

Thank you for reporting!
