### ISSUE TITLE
Production usage

### ISSUE THREAD

**Issue by saifat29** [buraksezer/olric#44]
I like this project and would like to use it in a heavy duty production environment.
How stable are the APIs and is it being used in production?

**Comment by buraksezer** [comment]
Hi,

Thank you for your interest. The API is mostly stable. So a breaking change is mostly unlikely to be happen. We have a few users who tries to integrate Olric into their production environment. 

https://github.com/buraksezer/olric/issues/9#issuecomment-588569127
https://github.com/buraksezer/olric/issues/6#issuecomment-640104297

I'm always here for support and further development. Would you like to say more about the usage scenario in production?

**Comment by saifat29** [comment]
I run multiple instances of the same Go based service each with their own in-memory cache [(go-cache)](https://github.com/patrickmn/go-cache) which are pre-loaded. To invalidate and update the cache all the instances subscribe to update events on Kafka. The throughput and latency performance is excellent with the current setup.

I am looking for an out-of-the-box solution and `olric` seems appropriate. However I'm more concerned about `olric`'s performance. For my use case read performance matters the most.


I'll benchmark `olric` against my current setup, only then I'll be able to make my mind.

**Comment by buraksezer** [comment]
> @buraksezer Good work with this project.

Thank you very much! 

> For my use case read performance matters the most.

That's great. With correct configuration, Olric should produce satisfying results. I advice some values for the critical parameters.

* **PartitionCount**: prime numbers are good. The default is 271 and it's good enough to shard large amount of keys.
* **ReadQuorum** and **WriteQuorum**: 1 is good for caching
* **ReadRepair**: this can be false for a cache deployment,
* **ReplicaCount**: 1 is good for cache deployment. The default value is 1.
* **Hasher**: xxhash is pretty good. It's default.

Olric implements an append-only log file, indexed with built-in map (uint64->uint64). So if the payload size is small, it should be run very fast. 

Routing algorithm is also very simple. Every node has an eventually consistent view of routing table and the nodes redirect incoming requests to the partition owner. 

`olric-load` is good for benchmarking: https://github.com/buraksezer/olric#olric-load

Thanks!

**Comment by derekperkins** [comment]
I know that you've targeted Kubernetes as a main deployment focus. How well does olric work for autoscaling pods? We have some very spiky workloads that will scale from 3 pods to 30 pods in a few minutes, then scale back down to 3.

**Comment by buraksezer** [comment]
@derekperkins Olric is able to discover cluster members on Kubernetes platform. I didn't try to produce this kind of heavy load in my test setup. If the autoscaling controller creates and kills the nodes very fast, the cluster may not be rebalanced. Olric moves partitions to new nodes in the case of node join. Ideal partition size should be around ~100MB. Normally a partition should be moved to the its new home in a few seconds. I think it should work seamlessly under moderate load, but I need to test this kind of scenarios. 

By the way, a Kubernetes operator implementation is probably needed to handle these kind of extreme scenarios. I'm going to investigate this. If you share more information about your case, it would be awesome. I'm always open for cooperation.

Cheers.

**Comment by ivanjaros** [comment]
so is this library essentially an in-memory etcd?

**Comment by buraksezer** [comment]
> so is this library essentially an in-memory etcd?

@ivanjaros Actually, Etcd is a completely different thing. It's a strongly consistent data store while Olric is an eventually consistent one. Basically, Olric is designed and built to store large amount of in-memory data on many computers with a minimum coordination between servers. 

https://www.allthingsdistributed.com/2008/12/eventually_consistent.html
https://hackernoon.com/eventual-vs-strong-consistency-in-distributed-databases-282fdad37cf7
https://stackoverflow.com/questions/10078540/eventual-consistency-in-plain-english

**Comment by ivanjaros** [comment]
eventual constisteny - gotcha.

**Comment by buraksezer** [comment]
@ivanjaros Great! Please don't hesitate to contact me to ask any question about the internals of Olric and integration problems.
