### ISSUE TITLE
Ordered delivery mode for DTopic data structure

### ISSUE THREAD

**Issue by buraksezer** [buraksezer/olric#45]
The current implementation of DTopic is designed to distribute key events (eviction, update, delete etc) across the cluster members and clients. It's totally random order. We need to implement an ordered delivery mode to satisfy different business requirements. 

Here is some inspiration: https://docs.hazelcast.org/docs/4.0.2/manual/html-single/index.html#understanding-topic-behavior

**Comment by billylindeman** [comment]
I'm curious what the roadmap for this looks like? Is this complex to implement on top of olric?  @buraksezer

**Comment by buraksezer** [comment]
There is no plans to build the ordered delivery mode in the near future. This topic may be revisited in 2021. If you are interested in DTopic and ordered delivery, I would like to learn more about your potential use case and deployment scenario. 

You should also feel free to send a design document and PR for this.

>  Is this complex to implement on top of olric?

I think it's more complex than the unordered mode. We probably need a queue implementation, but replicating a data structure is a challenging task. We may build this feature on top of a non-replicated queue, but this time every queue (namely ordered DTopic) is only hosted by a cluster member. So we lost high availability in this case.
