### ISSUE TITLE
memcache protocol implementation

### ISSUE THREAD

**Issue by buraksezer** [buraksezer/olric#47]
We need to implement memcache protocol in Olric to increase integration surface. Targed protocol is the text-based one. Firstly we need to investigate potential problems in the current implementation of DMap and related subsystems. Independent tasks should be spawn for improvements in the current implementation. 

Protocol specification: https://github.com/memcached/memcached/blob/master/doc/protocol.txt
Memcache client implementation in Golang: https://github.com/bradfitz/gomemcache/memcache

This task should be implemented after merging #28. feature/issue-28 contains important improvements on TCP server implementation and flow control.  

Any help would be appreciated.

**Comment by buraksezer** [comment]
Useful docs from Oracle: https://docs.oracle.com/cd/E17952_01/mysql-5.0-en/ha-memcached-interfaces-protocol.html

**Comment by ei09010** [comment]
Hi, I wouldn't mind implementing the memcached protocol if no one else is doing it.

**Comment by buraksezer** [comment]
Hi @ei09010 

Thank you for your interest. Memcached protocol implementation in Olric is a non-trivial task. So it requires great insight about internals of Olric and Memcached. It'll probably implemented by me but there is no planning for this in a foreseeable future. 

You can still work on this as an independent implementation. Here is my experiments with Memcached: https://github.com/buraksezer/memcached/tree/experimental

Your contributions to Olric is wellcome. We need testers and early adopters. Just using Olric and reporting bugs and proposing new features are great ways to contribute.

**Comment by ei09010** [comment]
Hi @buraksezer 

Thanks for the feedback.

My take on this implementation isto add the memcache protocol commands to Olric(https://docs.oracle.com/cd/E17952_01/mysql-5.0-en/ha-memcached-interfaces-protocol.html) and use the Dmap and it storage engine underneath. I added a draft for the Set command: https://github.com/ei09010/olric.

Based on your experimentation, am I right to assume that this isn't the right approach ?

Thank you for your time!

**Comment by buraksezer** [comment]
Olric now uses [RESP](https://redis.io/topics/protocol) for communication. There is no need to implement other protocols for wider adoption.
