### ISSUE TITLE
Set and manage maximum number of clients

### ISSUE THREAD

**Issue by buraksezer** [buraksezer/olric#51]
Currently we don't have any mechanism to limit the maximum number of clients that could be handled simultaneously. 

This feature should be designed properly. Here is some clue: https://redis.io/topics/clients#maximum-number-of-clients

**Comment by yashschandra** [comment]
Hey @buraksezer I find this project interesting and want to contribute. Can I take this issue?

**Comment by buraksezer** [comment]
Hi @yashschandra Thank you for your interest. It's yours. You should create your branch from master. It's good to see the improvements on [feature/issue-70](https://github.com/buraksezer/olric/tree/feature/issue-70).

Please feel free to ask questions on any platform: 

1. Here, obviously.
2. https://github.com/buraksezer/olric/discussions
3. https://olriclabs.slack.com/join/shared_invite/zt-jl6s0lg7-UghzN48XhHnZcKYp4akw3w#/

**Comment by buraksezer** [comment]
I'm closing this. Olric now uses [RESP](https://redis.io/topics/protocol) for communication. We use [go-redis/redis](https://github.com/go-redis/redis) as client implementation. It implements all these features.
