### ISSUE TITLE
Provide an API tho introspect the cluster state

### ISSUE THREAD

**Issue by cobexer** [buraksezer/olric#56]
In order to communicate liveness and readiness to the Kubernetes cluster, I would like to have some visibility into the olric cluster health.

For example:
If the current node can't communicate with the requested number of nodes to satisfy WriteQuorum I want to mark the current node as not ready in terms of Kubernetes so it stops receiving traffic from clients, or even as not live to get the pod restarted.

**Comment by buraksezer** [comment]
I am closing this issue due to a lack of interest.
