### ISSUE TITLE
Provide stats in Prometheus compatible exposition format to make integration into Kubernetes environments simpler

### ISSUE THREAD

**Issue by cobexer** [buraksezer/olric#57]
While there is an effort underway to standardize on https://openmetrics.io/ the current industry standard is still Prometheus metrics.

Having olric metrics available in Promethus compatible text format would allow very simple integration into a Kubernetes based service.

**Comment by buraksezer** [comment]
This feature is planned for v0.4.0. https://github.com/buraksezer/olric/issues/33

**Comment by buraksezer** [comment]
I am closing this issue due to a lack of activity.
