### ISSUE TITLE
Expose leader election events to the application

### ISSUE THREAD

**Issue by cobexer** [buraksezer/olric#58]
I haven't checked the internals too closely, so this may be a silly request...

If there is some sort of leader election happening inside an olric cluster expose the results to the embedding application.

For my use case I would only connect to the Kubernetes API from the leader because all nodes write the same data anyway and that way I could avoid useless duplicated write traffic.

**Comment by buraksezer** [comment]
This feature is planned for the v0.4.0 release. I have implemented **DTopic** data structure to implement event listeners correctly. It will probably be delivered by the first months of 2021 if everything goes okay. 

I have just added a field called `ClusterCoordinator` to `Stats`. You can call `db.Stats()` function periodically to learn who the cluster coordinator is. I know that this is not an optimal way to implement what you want to do, but I think that it's good enough for now. The leader election should be a very rare event. 

**Annotation:** The oldest member of the cluster is the cluster coordinator. It's role is totally different than the leader node in Raft or Paxos based systems such as etcd or any strongly consistent data store. 

If the cluster coordinator dies, the second oldest member of the cluster propagates itself as the cluster coordinator.

**Comment by buraksezer** [comment]
As I mentioned before, there is no leader election event in Olric. The oldest member of the cluster is the coordinator member and it pushes the routing table to the other members. This is the only responsibility of the coordinator. 

We may publish `NodeJoin` and `NodeLeft` events to cluster and the clients. We also have the basic building blocks to implement such a feature. If someone wants to build this feature, please don't hesitate to open an issue to discuss it.
