### ISSUE TITLE
Expose metadata

### ISSUE THREAD

**Issue by dunglas** [buraksezer/olric#63]
It could be useful to be able to access to the metadata associated with an entry, especially the insertion date and the TTL. It's basically what is `VData`, maybe could we add a method exposing it?

**Comment by buraksezer** [comment]
It's a good idea and relatively easy to implement. But I'm now sure about the name and the function signature. How is this? 

`DMap.GetMetadata(key) (Metadata, error)`

Actually, I would like to implement such a feature by adding methods or fields to the return type of `Get` method, but it returns a byte slice and it's not possible to break the API now. Take a look at this: https://pkg.go.dev/github.com/bradfitz/gomemcache/memcache#Client.Get

We may find a better way to build such features.

**Comment by dunglas** [comment]
Maybe can you just add a new `GetWithMetadata` function returning and instance of `Vdata` instead of a by slice?
It could be nice (and probably faster) to be able to access data and metadata in just one call.

**Comment by buraksezer** [comment]
@dunglas It's on the master branch. If `GetEntry` is okay for you, I'm going to release a new beta.

```
entry, err := dm.GetEntry("my-key")
```

Definition of `Entry`:

```go
type Entry struct {
	Key       string
	Value     interface{}
	TTL       int64
	Timestamp int64
}
```

**Comment by dunglas** [comment]
@buraksezer awesome! LGTM
