### ISSUE TITLE
Validate the configuration before running an Olric node

### ISSUE THREAD

**Issue by buraksezer** [buraksezer/olric#68]
We need to validate and sanitize the configuration. We already have this feature at some degree, but it's not good enough and poorly implemented. Every configuration struct has its own validator/sanitizer and these functions have to be called before running an Olric node.

Here is a sample. `config.Client` has its own `Sanitize` function and constructor. 

```go
// NewClient returns a new configuration object for clients.
func NewClient() *Client {
	c := &Client{}
	c.Sanitize()
	return c
}

// Sanitize sanitizes the given configuration.
func (c *Client) Sanitize() {
	if c.DialTimeout <= 0 {
		c.DialTimeout = DefaultDialTimeout
	}

	switch c.ReadTimeout {
	case -1:
		c.ReadTimeout = 0
	case 0:
		c.ReadTimeout = DefaultReadTimeout
	}

	switch c.WriteTimeout {
	case -1:
		c.WriteTimeout = 0
	case 0:
		c.WriteTimeout = DefaultWriteTimeout
	}

	if c.MaxConn == 0 {
		c.MaxConn = 1
	}
}
```

**Comment by gracehop** [comment]
Help me with this please  I do not seem to understand

**Comment by buraksezer** [comment]
@gracehop thank you for your interest but this issue is no more eligible for the newcomers. Because of the improvements in #46, this issue requires too much experience and knowledge about internals of Olric.

**Comment by buraksezer** [comment]
Merged into master
