### ISSUE TITLE
Issues with replicas and scaling

### ISSUE THREAD

**Issue by suederade** [buraksezer/olric#74]
Hey guys, I'm trying to get Olric to work in AWS environment and running into some pretty substantial issues. Because of our deployment process we deploy-one then deploy-all. The first node loads a large amount of data, then a second node will come up and successfully attach (using the consul plugin). I can query the data from the new node that is set as the backup and it successfully gets the data, although it seems to emit hundreds of thousands of errors `[ERROR] Failed to call get on a replica owner: <ip>: key not found`.

Another problem that happens is when I scale up the instances (e.g. 2 instances to 4), I basically get catastrophic errors that kill the service. It always seems to happen the same way.

First error is `operation timeout` from creating a new DMap. The app seems to restart and be successful the next time.

Second, gob won't register the type `gob: name not registered for interface: "*models.Product"`.

Third we get a massive error (that gets cut off, sorry) 

`when calling get dial tcp <ip>:8080: connect: cannot assign requested address: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal server error: internal se` The nodes seem to think that they connect just fine according to the beginning of the logs.

I have it set up with 120 partitions, replica count of 2.

I'm also getting write quorum not reached errors with a quorum count of 1

**Comment by suederade** [comment]
Sorry, probably missed some useful information:

go v1.15
olric v0.2.0
olric-consul-plugin v0.0.0-20200812193932-b7249b593406

**Comment by buraksezer** [comment]
Olric v0.2.0 is an outdated version. You should use v0.3.3. It includes many new features and bug fixes. 

> I have it set up with 120 partitions, replica count of 2.

Not quite important but partition number should be a prime number. Here is some math: https://medium.com/swlh/why-should-the-length-of-your-hash-table-be-a-prime-number-760ec65a75d1

> [ERROR] Failed to call get on a replica owner: <ip>: key not found

That's normal. If you don't want to see these kind of messages, you feel free to decrease verbosity level by configuration. Here is the default config:

```yaml
logging:
  verbosity: 6
  level: "DEBUG"
  output: "stderr"
```

`verbosity: 3` is good enough for most users.

Would you like to explain your deployment scenario? Embedded-member or server-client?

**Comment by suederade** [comment]
@buraksezer Sorry, for the late reply. Deadlines! Doh, I thought I was using v0.3! We are using it as an embedded-member as we have to have low latency, high availability API, so we wanted the data to be on RAM in easy access. I can try it out with the lower logging and verbosity. I will try out and read up on the why your partitions should be a prime number.

**Comment by buraksezer** [comment]
I'm closing this due to lack of the response. Please feel free to open this issue again, if you still have problems.
